[project]
name = "python-dataframe-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.0",
    "dask[all]>=2025.9.1",
    "pandas>=2.3.3",
    "polars[all]>=1.34.0",
    "pyarrow>=21.0.0",
]
